#
# James Sandoval
# CS372 
# Makefile: Project 2
# This is the makefile for the file server
# written in c.
#

PROGS := server

all: $(PROGS)

server: fileserver.c
	g++ -g fileserver.c -o fileserver

clean:
	rm -f $(PROGS) *.o *~



