

#
# James Sandoval
# CS372 
# Makefile: Project 1
# This is the makefile for the client
# written in c.
#
PROGS := client

all: $(PROGS)

client: client.c
	g++ -g client.c -o client


clean:
	rm -f $(PROGS) *.o *~



